### Project specific config ###
language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.1.8
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.2.5
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.3.1
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.3.1
      env: ATOM_CHANNEL=beta

env:
  global:
    # For regular user installations this will be taken care of by package-deps
    # However, package activation doesn't wait on the Promise that returns so
    # we are just forcing it's installation here.
    - APM_TEST_PACKAGES="language-haml"
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

install:
  # Installed for linting the project
  - nvm install node
  - gem install --no-document haml_lint

before_script:
  - haml-lint --version

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
