### Project specific config ###
language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.1.8
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.2.6
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.3.3
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.3.3
      env: ATOM_CHANNEL=beta

env:
  global:
    # For regular user installations this will be taken care of by package-deps
    # However, package activation doesn't wait on the Promise that returns so
    # we are just forcing it's installation here.
    - APM_TEST_PACKAGES="language-haml"

install:
  - gem install --no-document haml_lint

before_script:
  - haml-lint --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^greenkeeper/.*$/

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
