# Project specific configuration
language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1

env:
  global:
    # For regular user installations this will be taken care of by package-deps
    # However, package activation doesn't wait on the Promise that returns so
    # we are just forcing it's installation here.
    - APM_TEST_PACKAGES="language-haml"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux

# Generic configuration
notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

git:
  depth: 10

branches:
  only:
    - master

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
